# Redis only.
#   docker compose -f deploy/compose/docker-compose.redis.yml up -d
name: geofastmap_api

services:
  redis:
    restart: unless-stopped
    image: redis:7-alpine
    container_name: geofastmap_redis
    ports:
      - "6379:6379"
