from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    app_name: str = "GeoFastMap API"
    environment: str = "development"

    # Example: postgresql+asyncpg://user:password@localhost:5432/geofastmap
    database_url: str = (
        "postgresql+asyncpg://postgres:postgres@localhost:5432/geofastmap"
    )
    # Connection pool: increase for heavy concurrent load (e.g. dynamic tiles). Default 5+10 is too low for maps.
    database_pool_size: int = 20
    database_pool_max_overflow: int = 20
    database_pool_timeout: float = 30.0  # seconds to wait for a connection from the pool

    # OGC API Features items: pagination limits
    items_default_limit: int = 100
    items_max_limit: int = 1000
    # Max vertices per feature row; geometries are subdivided at insert via ST_Subdivide(geom, N).
    features_subdivide_max_vertices: int = 256
    # Max size of one geometry (OGC WKB byte length). Rejects API writes and skips bulk-import parts over limit.
    features_max_geometry_bytes: int = 50 * 1024 * 1024  # 50 MiB; set 0 to disable

    # Bulk import: batch size for DB inserts (background job)
    bulk_import_batch_size: int = 1000

    # Bulk storage: where uploaded files go (shared path for API and worker). Future: s3.
    bulk_storage_type: str = "filesystem"  # filesystem | s3 (s3 reserved)
    bulk_storage_path: str = "/data/bulk-uploads"  # for filesystem; create if missing

    # Bulk queue: memory = in-process consumer; redis = separate worker(s), scalable.
    bulk_queue_type: str = "redis"  # memory | redis
    redis_url: str = "redis://localhost:6379/0"  # used when bulk_queue_type=redis

    # OGC API - Processes: geometric operations (intersection, erase) between collections.
    process_queue_type: str = "redis"  # redis | memory (memory = no separate worker)
    process_max_concurrent: int = 1  # max process jobs running at once per worker
    # Stream A in batches by memory size. Keep low to limit worker RAM (each batch + B in bbox held in memory).
    process_batch_max_bytes: int = 256 * 1024  # max bytes of geometry (A) per batch (default 256 KiB)
    process_batch_max_rows: int = 0  # optional cap: max rows per batch (0 = only byte limit)
    process_insert_batch_size: int = 200  # rows per INSERT commit when writing results (smaller = less memory)
    # Max batch results held before inserting (1 = write as soon as one batch completes; minimizes memory).
    process_max_pending_batches: int = 1
    # Parallel batch workers per job (0 = use CPU count). Lower = less memory (fewer concurrent batches).
    process_batch_workers: int = 0  # 0 = os.cpu_count(), else cap threads per job
    process_progress_update_seconds: float = 2.0  # how often to update job progress (items_in/items_created)
    # Intersection pair-based flow: chunk size when reading (id_a, id_b) pairs and fetching those two features only.
    process_intersection_pair_chunk_size: int = 400  # pairs per chunk (each chunk = 2 bounded feature fetches)
    # Temp directory for process worker; cleaned on startup. Set empty to disable cleanup.
    process_temp_path: str = "/tmp/geofastmap_process_worker"
    # Statement timeout (seconds) for process worker DB connections. 0 = disabled. Helps prevent long queries from blocking API.
    process_worker_statement_timeout_seconds: int = 0  # 0 = no limit; e.g. 1800 = 30 min max per statement

    # Tiles: static MBTiles storage; dynamic tiles are served by FastAPI from PostGIS.
    tiles_storage_path: str = "/data/tiles"
    # Max features per MVT tile to avoid overloading the database (default 200k).
    tiles_mvt_max_features: int = items_max_limit
    # Redis cache TTL for dynamic tiles (seconds). 0 = no cache.
    tiles_dynamic_cache_ttl_seconds: int = 60
    # Also cache tiles with query params (limit, offset, bbox, etc.) to reduce DB load when panning/zooming.
    tiles_dynamic_cache_with_params: bool = True
    # TTL for parametrized tile cache (seconds). Max 60 to limit staleness; use invalidate button for immediate refresh.
    tiles_dynamic_cache_params_ttl_seconds: int = 60
    # Max time (seconds) for a single dynamic tile query; 0 = disabled. Helps avoid holding pool connections.
    tiles_dynamic_statement_timeout_seconds: int = 15
    # When set, dynamic tiles are generated by this worker (DB + tippecanoe). Empty = use in-process PostGIS MVT.
    tiles_dynamic_worker_url: str = ""  # e.g. http://localhost:8001
    # When non-empty, use Redis search cache + tile job queue (workers read from cache, no DB). e.g. "1" or "true".
    tiles_dynamic_use_queue: bool = False
    # TTL for cached search result GeoJSON (seconds). Workers read from this; no DB in workers. Max 60 to limit staleness.
    tiles_search_result_cache_ttl_seconds: int = 60
    tippecanoe_path: str = "tippecanoe"  # PATH or full path to tippecanoe binary
    tippecanoe_minzoom: int = 0
    tippecanoe_maxzoom: int = 16
    google_maps_api_key: str = ""  # optional; for Google Satellite/Hybrid basemaps in HTML

    # Rasters: COG storage (shared with Titiler worker when using file:// URLs)
    raster_storage_path: str = "/data/rasters"
    raster_upload_max_bytes: int = 500 * 1024 * 1024  # 500 MiB
    # Internal Titiler base URL (e.g. http://titiler:8000). Empty = proxy disabled / in-app tiles only.
    titiler_internal_url: str = ""
    # Shared secret for Titiler → API internal COG fetch (optional; avoids file:// in Titiler).
    titiler_internal_secret: str = ""
    # Base URL reachable from the Titiler container for internal COG fetch (e.g. http://api:8000).
    raster_internal_fetch_base_url: str = ""
    # Redis cache for proxied Titiler raster tiles (STAC item viewer). 0 = disabled.
    # Cold tiles still cost GDAL+network; repeats (pan/zoom back) hit Redis ~1–5 ms.
    titiler_tile_cache_ttl_seconds: int = 3600
    # Do not store responses larger than this (bytes); avoids huge entries from mistakes.
    titiler_tile_cache_max_body_bytes: int = 4 * 1024 * 1024
    # Federated STAC Item Search: Redis cache TTL (seconds). 0 = no cache.
    stac_search_cache_ttl_seconds: int = 300
    stac_search_http_timeout_seconds: float = 60.0
    # Federated STAC: retry POST /search on transient upstream errors (502/503/504/429).
    stac_search_http_max_retries: int = 2  # attempts after the first (2 => up to 3 tries per catalog)
    stac_search_http_retry_backoff_seconds: float = 0.75  # base delay; exponential backoff
    stac_search_max_catalogs: int = 32
    # HTML STAC search: max merged features fetched before slicing for pagination (per search).
    stac_search_html_max_features: int = 2000
    # Max page size for GET /stac?f=html
    stac_search_html_max_limit: int = 100

    # Auth: session signing key (set in production); empty = no session auth
    auth_secret_key: str = ""
    # Default admin credentials for first-time seed (change after first login)
    auth_default_admin_username: str = "admin"
    auth_default_admin_password: str = "admin"

    @property
    def database_sync_url(self) -> str:
        """URL for sync SQLAlchemy (background threads). Replaces asyncpg with psycopg2."""
        if "+asyncpg" in self.database_url:
            return self.database_url.replace("+asyncpg", "+psycopg2", 1)
        if self.database_url.startswith("postgresql://"):
            return self.database_url  # psycopg2 default
        return self.database_url

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
    )


@lru_cache
def get_settings() -> Settings:
    return Settings()

